spring.application.name=sentinel_api

api.security.token.secret=${JWT_SECRET:123}

spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_db
spring.datasource.username=admin
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true